// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9uEkz4LevF_gjVLo6GMV1BUFbd0y6XC0',
    appId: '1:280621792365:web:cb6e0191a1c076b5825364',
    messagingSenderId: '280621792365',
    projectId: 'family-zone-2026',
    authDomain: 'family-zone-2026.firebaseapp.com',
    storageBucket: 'family-zone-2026.firebasestorage.app',
    measurementId: 'G-BFLRWCR46J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH5NlU9MkUhzKQ_zu3Jzx47VDPlA5ByM4',
    appId: '1:280621792365:android:f330bce2f04ca66d825364',
    messagingSenderId: '280621792365',
    projectId: 'family-zone-2026',
    storageBucket: 'family-zone-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB74u7_Z4_85s-7zRz_F1OZc-dOGrkg4Og',
    appId: '1:280621792365:ios:51e4639675c1a716825364',
    messagingSenderId: '280621792365',
    projectId: 'family-zone-2026',
    storageBucket: 'family-zone-2026.firebasestorage.app',
    iosBundleId: 'com.familyzone.shop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB74u7_Z4_85s-7zRz_F1OZc-dOGrkg4Og',
    appId: '1:280621792365:ios:51e4639675c1a716825364',
    messagingSenderId: '280621792365',
    projectId: 'family-zone-2026',
    storageBucket: 'family-zone-2026.firebasestorage.app',
    iosBundleId: 'com.familyzone.shop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9uEkz4LevF_gjVLo6GMV1BUFbd0y6XC0',
    appId: '1:280621792365:web:5f1ed13e2691a76e825364',
    messagingSenderId: '280621792365',
    projectId: 'family-zone-2026',
    authDomain: 'family-zone-2026.firebaseapp.com',
    storageBucket: 'family-zone-2026.firebasestorage.app',
    measurementId: 'G-EY67LHWEH5',
  );
}
